name: Github Runner Robot
on:
  push:
    branches:
      - "github-runner-robot"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_AUTHTOKEN }}
    steps:
      - name: Install network-manager tool
        run: |
          sudo apt-get update
          sudo apt-get install network-manager
          systemctl start NetworkManager.service
          nmcli device status
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Run docker robot
        run: docker-compose up -d
      - name: Run establish a ngrok tunnel
        uses: vmactions/ngrok-tunnel@v0.0.1
        with:
          protocol: http
          port: 31950
      - name: Sleep for 900 seconds
        run: sleep 900s
        shell: bash